<?php

declare(strict_types=1);

namespace Devly\WP\Routing\Tests\Integration;

use Devly\DI\Container;
use Devly\WP\Routing\Router;
use WP_Ajax_UnitTestCase;
use WPAjaxDieContinueException;

class AjaxRoutingTest extends WP_Ajax_UnitTestCase
{
    protected string $action = 'test_route';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->router = new Router(new Container([], true, true));

        $this->router->ajax($this->action, static fn () => 'foo');

        do_action('admin_init');
    }

    public function testAjaxRouteAppliedToWordpress(): void
    {
        try {
            $this->_handleAjax($this->action);
        } catch (WPAjaxDieContinueException $e) {
        }

        $this->assertTrue(
            has_action('wp_ajax_nopriv_test_route'),
            '`wp_ajax_nopriv_{$action}` action hook should not be applied'
        );

        $this->assertTrue(
            has_action('wp_ajax_test_route'),
            '`wp_ajax_{$action}` action hook should be applied'
        );
    }
}
